### ISSUE TITLE
Charm is not present in Juju charm store

### ISSUE THREAD

**Issue by edvinas31** [gabriel-samfira/charm-magnum#1]
Why this charm is not available in Juju charm store? Could it be deployed along openstack-base charms? https://jaas.ai/search?type=charm

**Comment by gabriel-samfira** [comment]
This charm was written a long time ago as an experiment, and to try something out. The reason it was never uploaded to the charm store, is because I never needed it after that initial experiment. I simply forgot about this repository.

I may update this charm at some point, but I have a huge backlog to take care of first :)
